### ISSUE TITLE
Multiple errors when pushing scenario configs (Specific to IPv6 configs so far ONLY)

### ISSUE THREAD

**Issue by OfWolfAndMan** [OfWolfAndMan/CCIE-Lab-Automation#2]
Errors shown as below (For a single thread). Likely issue with the threading module, not sure what is throwing the "paramiko.buffered_pipe.PipeTimeout" error:

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 683, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/buffered_pipe.py", line 160, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 377, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 685, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Automatelab.py", line 493, in scenario_configuration_install
    output = net_connect.send_config_set(command_set)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1131, in send_config_set
    output += self.exit_config_mode()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/cisco_base_connection.py", line 51, in exit_config_mode
    pattern=pattern)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1081, in exit_config_mode
    if self.check_config_mode():
  File "/usr/local/lib/python3.6/dist-packages/netmiko/cisco_base_connection.py", line 33, in check_config_mode
    pattern=pattern)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1065, in check_config_mode
    output = self.read_until_pattern(pattern=pattern)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 449, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 384, in _read_channel_expect
    raise NetMikoTimeoutException("Timed-out reading channel, data not available.")
netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "Automatelab.py", line 495, in scenario_configuration_install
    except netmiko.ssh_exception.NetMikoTimeoutException:
NameError: name 'netmiko' is not defined
```

**Comment by shubhamnetmiko** [comment]
Mine worked after changing privilege level of user to 15..
